/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cyberplaysoftware1;

import ConexionBd.CBDPLAY;
import com.mysql.jdbc.Connection;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Gtecno
 */
public class ModPrincipal extends javax.swing.JFrame {
    String Ho,Hora,Hora2,Horaf,est,cedu,acti="INGRESO",fech,nom,sa="0",est2,con2,rol; 
     CBDPLAY cc = new CBDPLAY();
 Connection cn = ( Connection) cc.Conectar();
 
   String SQL,SQL2,SQL3,SQL4;
   ResultSet rs;
    
    /**
     * Creates new form ModPrincipal
     */
    public ModPrincipal() {
         setUndecorated(true);
        initComponents();
          setLocationRelativeTo(null);
          
       this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        i();
         nombre();
    }
void i(){
    Image icon;
    icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/ico.png"));
    
            
            
    setIconImage(icon);
    setVisible(true);
  }
void nombre()
  {
    try
    {
         String SQL5="SELECT * FROM usuario  WHERE estado <> 0   ";       
      Statement st5 = (Statement) cn.createStatement();   
      ResultSet rsu =   st5.executeQuery(SQL5);
      while (rsu.next()){   
        est=rsu.getString("estado");  
          cedu=rsu.getString("cedula_usuario");
          //nom=rsu.getString("nombre");
                        }
         
         
     Statement   st = this.cn.createStatement();
       rs = st.executeQuery("SELECT * FROM usuario  WHERE cedula_usuario ='"+cedu+"'   ");
      rs.last();
      
      int encontrado = rs.getRow();
      if (encontrado == 1)
      {
        String SQL = " SELECT * FROM usuario WHERE cedula_usuario ='"+cedu+"'";
        
        Statement sv = null;
        sv = this.cn.createStatement();
        ResultSet rv = sv.executeQuery(SQL);
        rv.next();
        String nomz,apez,ruta1;
       
       nomz=rv.getString("nombre_usuario");
       apez=rv.getString("apellido_usuario");
       nomjb.setText(" USUARIO:"+" "+nomz+" "+apez);
      // rol = rv.getString("rol");
        ruta1=rv.getString("rutafoto_usuario");
    
       
   
      
      
     
   
    
        
        File ruta = new File(ruta1);
           
            String d=(String.valueOf(ruta));
          
            Image foto= getToolkit().getImage(d);
            
            foto= foto.getScaledInstance(60, 60, Image.SCALE_DEFAULT);
          
          lbfoto.setIcon(new ImageIcon(foto));
        }
      
      else
      {
        JOptionPane.showMessageDialog(null, "0", "ERROR", 0);
      }
      rs.close();
      st.close();
    }
    catch (Exception e) {}
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lbicop = new javax.swing.JLabel();
        nomjb = new javax.swing.JLabel();
        lbfoto = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CyberPlayPagos ");

        jPanel1.setBackground(new java.awt.Color(13, 92, 216));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(13, 92, 216));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Android", 1, 14)); // NOI18N
        jButton1.setText("Gestión de Cliente>");
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 220, 200, 42);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Android", 1, 14)); // NOI18N
        jButton2.setText("Cuenta del Cliente>");
        jButton2.setBorder(null);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(210, 220, 220, 42);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Android", 1, 14)); // NOI18N
        jButton3.setText("Tarjeta de Cliente>");
        jButton3.setBorder(null);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(430, 220, 200, 42);

        lbicop.setBackground(new java.awt.Color(100, 196, 242));
        lbicop.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        lbicop.setForeground(new java.awt.Color(255, 255, 255));
        lbicop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbicop.setOpaque(true);
        jPanel2.add(lbicop);
        lbicop.setBounds(0, 60, 640, 160);

        nomjb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nomjb.setForeground(new java.awt.Color(255, 255, 255));
        nomjb.setText("jLabel2");
        jPanel2.add(nomjb);
        nomjb.setBounds(10, 10, 250, 30);

        lbfoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbfoto.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        lbfoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbfoto);
        lbfoto.setBounds(470, 0, 70, 60);

        jButton5.setBackground(new java.awt.Color(0, 204, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        jButton5.setText("Salir");
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setOpaque(true);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(540, 0, 100, 30);

        jButton6.setBackground(new java.awt.Color(0, 102, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/next.png"))); // NOI18N
        jButton6.setText("Minimizar");
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setOpaque(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(540, 30, 100, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 644, 270);

        jLabel1.setFont(new java.awt.Font("Android", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 644, 460);

        jMenu1.setText("SEGURIDAD");

        jMenuItem1.setText("Gestión de Usuario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem4.setText("Respaldo de Datos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Restauración de Datos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("INFORMACIÓN");

        jMenuItem6.setText("Información de Sofware");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new ModGesCliente().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered

        File   ruta2 = new File("C:/Archivos de programa/CyberPlaySoftware/Graficos/calculator (1).png");
           String a=(String.valueOf(ruta2));
          Image foto2= getToolkit().getImage(a);
         lbicop.setIcon(new ImageIcon(foto2));  
          lbicop.setText("Paso 2");
          lbicop.setBackground(new java.awt.Color(66, 145, 27));
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
       File   ruta2 = new File("C:/Archivos de programa/CyberPlaySoftware/Graficos/Client_Male_Dark (1).png");
           String a=(String.valueOf(ruta2));
          Image foto2= getToolkit().getImage(a);
         lbicop.setIcon(new ImageIcon(foto2));  
          lbicop.setText("Paso 1");
          lbicop.setBackground(new java.awt.Color(104,236,245));    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
         File   ruta2 = new File("C:/Archivos de programa/CyberPlaySoftware/Graficos/Imagen1.png");
           String a=(String.valueOf(ruta2));
          Image foto2= getToolkit().getImage(a);
         lbicop.setIcon(new ImageIcon(foto2));  
          lbicop.setText("Paso 3");
          lbicop.setBackground(new java.awt.Color(100,196,242)); // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new ModRecarCliente().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   new ModGenTarj().setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
new ModSeguRegi().setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
int resp = JOptionPane.showConfirmDialog(this, "¿Deseas Salir?", "Salida de Sistema", 0);
      if (resp == 0) {
     
   
          try {
           
          //  sa = "1";
          //  acti = "SALIDA";
            
            PreparedStatement psd;
            SQL = "UPDATE usuario set estado=? WHERE estado <>?  ";

            psd =  cn.prepareStatement(SQL);
            psd.setString(1, "0");
            psd.setString(2, "0");
           

            int f = psd.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error SQL ");
        }
      //  fpa();
        System.exit(0);
      }
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
this.setExtendedState(ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

            int opcion = JOptionPane.showConfirmDialog(null, "¿Quieres generar respaldo de base de datos cyberplay?", "Mensaje del sistema", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                try {
                    Process p = Runtime
                            .getRuntime()
                            .exec("mysqldump --opt --password=Gtecno12345678 --user=root --databases cyberplay");

                    InputStream is = p.getInputStream();
                    Date date = new Date();
                    DateFormat df = new SimpleDateFormat("dd-MM-yyyy");
                    File f = new File("C:/cyberplay");
                    f.mkdirs();
                    FileOutputStream fos = new FileOutputStream("C:/cyberplay".concat(File.separator).concat("cyberplay").concat("_").concat(df.format(date)).concat(".sql"));
                    byte[] buffer = new byte[1000];

                    int leido = is.read(buffer);
                    while (leido > 0) {
                        fos.write(buffer, 0, leido);
                        leido = is.read(buffer);
                    }

                    fos.close();
                    JOptionPane.showMessageDialog(null, "RESPALDO COMPLETO", "Mensaje del sistema", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }        // TODO add your handling code here:
                // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

            JFileChooser fc = new JFileChooser("C:/cyberplay");
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("SQL", "sql");
            fc.setFileFilter(filtro);
            int respuesta = fc.showOpenDialog(null);
            if (respuesta == JFileChooser.APPROVE_OPTION) {
                File f = fc.getSelectedFile();
                try {
                    Process p = Runtime.getRuntime().exec("mysql --user=root --password=Gtecno12345678 --database  cyberplay");
                    OutputStream outputStream = p.getOutputStream();

                    byte[] buffer = new byte[1000];
                    FileInputStream fis = new FileInputStream(f);
                    int leido = fis.read(buffer);

                    while (leido > 0) {
                        outputStream.write(buffer, 0, leido);
                        leido = fis.read(buffer);
                    }
                    outputStream.flush();
                    JOptionPane.showMessageDialog(null, "RESTAURACIÓN COMPLETA", "Mensaje del sistema", JOptionPane.INFORMATION_MESSAGE);
                } catch (IOException ex) {
                    Logger.getLogger(ModPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            } // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
     new ModInfo().setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ModPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbfoto;
    private javax.swing.JLabel lbicop;
    private javax.swing.JLabel nomjb;
    // End of variables declaration//GEN-END:variables
}
