/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cyberplaysoftware1;

import ConexionBd.CBDPLAY;

import java.awt.Image;
import java.awt.Toolkit;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gtecno
 */
public class ModUsu extends javax.swing.JFrame {
   CBDPLAY cc = new CBDPLAY();
 Connection cn = ( Connection) cc.Conectar();
   
   ResultSet rs;
  String SQL,SQL2,SQL3,SQL4,cedu;
    /**
     * Creates new form ModUsu
     */
    public ModUsu() {
        setUndecorated(true);
        initComponents();
         this.setLocationRelativeTo(null);
       
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        i();
         
    }
       private static final char[] CONSTS_HEX = { '0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f' }; 
     public static String encriptaEnMD5(String stringAEncriptar)  
     {        
         try        {     
             MessageDigest msgd = MessageDigest.getInstance("MD5");      
             byte[] bytes = msgd.digest(stringAEncriptar.getBytes());     
             StringBuilder strbCadenaMD5 = new StringBuilder(2 * bytes.length); 
             for (int i = 0; i < bytes.length; i++)    
             {            
                 int bajo = (int)(bytes[i] & 0x0f);  
             int alto = (int)((bytes[i] & 0xf0) >> 4);    
             strbCadenaMD5.append(CONSTS_HEX[alto]);      
             strbCadenaMD5.append(CONSTS_HEX[bajo]);           }  
             return strbCadenaMD5.toString();      
         } catch (NoSuchAlgorithmException e) {         
             return null;        }  
     }     
    void i(){
    Image icon;
    icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/ico.png"));
    
            
            
    setIconImage(icon);
    setVisible(true);
  }
 void entrar() throws SQLException{
 
     String usuario=txtusu.getText();
     String password=txtpass.getText();
       if((usuario.isEmpty())||(password.isEmpty()))
       {
         JOptionPane.showMessageDialog(null,"ERROR: Campos Vacios!");
       }
       else
       {

       try
       { 
Statement  st1= (Statement) cn.createStatement();
        rs = st1.executeQuery("SELECT * FROM usuario  WHERE usuario_usuario ='"+encriptaEnMD5(usuario)+"' AND  contraseña_usuario='"+encriptaEnMD5(password)+"'");
         rs.last();

         int encontrado=rs.getRow();
        
         if(encontrado==1)
         {
             cedu=rs.getString("cedula_usuario");
           
               PreparedStatement psd;
            
             SQL="UPDATE usuario set estado=? WHERE cedula_usuario=?";
                psd = cn.prepareStatement(SQL);
                psd.setString(1,cedu);
                psd.setString(2,cedu);
                 int f=  psd.executeUpdate();
          
            
              this.dispose();
          ModPrincipal c= new   ModPrincipal();
            c.setVisible(true);
          
             
          
   
 
         }
         else
         {
            JOptionPane.showMessageDialog(null,"ERROR: Usuario o Contraseña no coinsiden!");
       txtusu.setText("");
        txtpass.setText("");
         }

        // rs.close();
        // st.close();
       }
       catch (Exception e)
      {
      }
       } }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtusu = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        btacep = new javax.swing.JButton();
        btsa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Android", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Seguridad");
        jLabel5.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CyberPlayPagos ");

        jPanel1.setBackground(new java.awt.Color(13, 92, 216));
        jPanel1.setLayout(null);

        txtusu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtusu);
        txtusu.setBounds(90, 70, 194, 30);

        txtpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        jPanel1.add(txtpass);
        txtpass.setBounds(90, 140, 194, 29);

        btacep.setBackground(new java.awt.Color(255, 255, 255));
        btacep.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btacep.setText("ACEPTAR");
        btacep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btacepActionPerformed(evt);
            }
        });
        jPanel1.add(btacep);
        btacep.setBounds(130, 180, 120, 35);

        btsa.setBackground(new java.awt.Color(0, 0, 0));
        btsa.setFont(new java.awt.Font("Android", 1, 14)); // NOI18N
        btsa.setForeground(new java.awt.Color(255, 255, 255));
        btsa.setText("Salir");
        btsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaActionPerformed(evt);
            }
        });
        jPanel1.add(btsa);
        btsa.setBounds(150, 230, 80, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Android", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Seguridad");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-6, -6, 390, 40);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USUARIO");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 40, 210, 21);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(-6, 224, 390, 50);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CONTRASEÑA");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 110, 210, 21);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/User.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 70, 30, 30);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lock.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 140, 34, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gtecno\\Desktop\\fondo.png")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 400, 270);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btacepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btacepActionPerformed
 try {
          
                entrar();
        } catch (SQLException ex) {
            Logger.getLogger(ModUsu.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btacepActionPerformed

    private void btsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btsaActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ModUsu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btacep;
    private javax.swing.JButton btsa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtusu;
    // End of variables declaration//GEN-END:variables
}
