/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cyberplaysoftware1;

import ConexionBd.CBDPLAY;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Gtecno
 */
public class NewJFrame extends javax.swing.JFrame {
      CBDPLAY cc = new CBDPLAY();
 Connection cn = cc.Conectar();
   Statement  st;ResultSet rs;
  String SQL,SQL2,SQL3,SQL4;
 private BigDecimal  faAmountOne;
         private BigDecimal  faAmountTwo;
          private static BigDecimal Two4;
          int d;
           double s;
          private static BigDecimal Two3= new BigDecimal(50);
        private static BigDecimal Two1= new BigDecimal(15200300.5);
        private static BigDecimal Two2= new BigDecimal(30500400.8);
          private BigDecimal getSum(){
             return faAmountOne.add(faAmountTwo);
              }
                  private BigDecimal getDifference(){
             return faAmountOne.subtract(faAmountTwo);
              }
                  BigDecimal MonedaCon1;
                   BigDecimal MonedaCon2;
                     public NewJFrame() {
      initComponents();
      //  big1();
       
    }
                     
                      void suma()
  {
    try
    {
        String Pago="transfe";
      SQL2 = "SELECT MAX(numero_referencia)  FROM  seguimiento_cuenta_cyberplay where  proceso_cuenta LIKE '%"+Pago+"%' ";
      
      Statement st2 = null;
      st2 = this.cn.createStatement();
      rs = st2.executeQuery(SQL2);
      rs.next();
      int q = rs.getInt("MAX(numero_referencia)");
     int v = (10 + q);
     
      
  jb1.setText("01"+String.valueOf(v));
    }
    catch (SQLException ex) {}
  }
			//  NumberFormat dispFormat = NumberFormat.getCurrencyInstance();
// Formato de edición: inglés (separador decimal: el punto)
//NumberFormat editFormat = NumberFormat.getNumberInstance(Locale.ENGLISH);
// Para la edición, no queremos separadores de millares
//editFormat.setGroupingUsed(false);
// Creamos los formateadores de números
//NumberFormatter dnFormat = new NumberFormatter(dispFormat);
//NumberFormatter enFormat = new NumberFormatter(editFormat);
// Creamos la factoría de formateadores especificando los
// formateadores por defecto, de visualización y de edición
//DefaultFormatterFactory currFactory = new DefaultFormatterFactory(dnFormat, dnFormat, enFormat);
// El formateador de edición admite caracteres incorrectos
//enFormat.setAllowsInvalid(true);
// Asignamos la factoría al campo
//jFormattedTextField1.setFormatterFactory(currFactory);
    /**
     * Creates new form NewJFrame
     */
 

    
                //    private void log(String aText){
      //  System.out.print(aText);  
              //}
       void formulaConver(){
   //  String ak=   jFormattedTextField1.getText();
   String as  = txbf.getText();
  //     fl(ak);
      ff(as);
    }
    public void fl(String... s){
  MonedaCon1= new  BigDecimal(s [0]);  
    
    }
     public void ff(String... s){
  MonedaCon2= new  BigDecimal(s [0]);  
    
    }
    void conver(){
      // MonedaCon1=   MonedaCon1.multiply(Two3); 
     //  String z=String.valueOf(MonedaCon1);
     // s =Double.valueOf(z);
      // b=Double.valueOf(String.valueOf(MonedaCon1));
     //   d= (int) Math.floor(s);
        MonedaCon2=   MonedaCon2.subtract(Two3); 
       // double b;
     //  b=Double.valueOf(String.valueOf(MonedaCon1));
     //   d= (int) Math.floor(b);
    }
     //  void big1 (){
     //  DecimalFormat dnFormat = new  DecimalFormat("#,##0.00");
      
// Para la edición, no queremos separadores de millares
    //  Two4=  Two1.add( Two2) ;
      // Two3= Two4.divide(Two3);
//editFormat.setGroupingUsed(false);
        ///   jLabel1.setText("BsF "+ dnFormat.format(Two1.add( Two2)));
           //jLabel2.setText("BsS "+  dnFormat.format( Two3));
    // }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jbr1 = new javax.swing.JLabel();
        txbf = new javax.swing.JTextField();
        jbf = new javax.swing.JLabel();
        jb1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jFormattedTextField1.setColumns(5);
        jFormattedTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextField1.setVerifyInputWhenFocusTarget(false);
        jFormattedTextField1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jFormattedTextField1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel1");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbf.setText("jLabel3");

        jb1.setText("jLabel3");

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(80, 80, 80)))
                        .addComponent(jButton1)
                        .addGap(64, 64, 64))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txbf, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbf, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbr1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 17, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txbf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jb1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextField1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jFormattedTextField1CaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1CaretPositionChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
formulaConver();
        conver();
//jbr1.setText(" "+d); 
jbf.setText(" "+MonedaCon2);
jLabel2.setText("BsS "+  d);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      suma();
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jb1;
    private javax.swing.JLabel jbf;
    private javax.swing.JLabel jbr1;
    private javax.swing.JTextField txbf;
    // End of variables declaration//GEN-END:variables
}
